import type { Metadata } from 'next'
import './globals.css'


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Travel Website',
  description: 'Generated by create next appTrave UI/UX App Layout',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">    
      <body>
       {children}
      </body>  
    </html>
  )
}
